### ISSUE TITLE
Legend

### ISSUE THREAD

**Issue by duncangeere** [Storythings/2017databreaches#11]
We should probably have a legend, no?

**Comment by edenbrack** [comment]
This legend would define Green Vs. Red circles, scale of circles, anything else?

**Comment by duncangeere** [comment]
I think that's all it needs to do, yeah.

**Comment by duncangeere** [comment]
I'm inclined to leave out scale of circles from legend, because that's already dual-encoded (x-position and size) and will take up a lot of room - particularly on mobile screens.

Which just leaves colour. I've made a very, very simple legend by extending the x-axis label, but it's too big for mobile now. I'll have another look at it this afternoon, perhaps.

![img_3014](https://user-images.githubusercontent.com/11523915/35507027-b40c00e2-04eb-11e8-916a-b53d9f2e0ab9.jpg)

**Comment by duncangeere** [comment]
I'm happy with this now.
