### ISSUE TITLE
Tooltips going off the side of the page

### ISSUE THREAD

**Issue by duncangeere** [Storythings/2017databreaches#13]
Right now, when the page is thin, some of the tooltips go off the sides. How do we prevent that?

**Comment by duncangeere** [comment]
Just noticed that the tap-off functionality is also not working for mobile. We should look into that too.

**Comment by edenbrack** [comment]
hey, i'm trying to figure out what the "if" needs to be. i'm thinking cx (the position of the dot on the x-axis) need to be greater than half of the x-axis range - would this be explicitly 10,000,000 or width/2? i seem to be breaking the graph when i try these things. please help if u can!

**Comment by duncangeere** [comment]
I'll take a look at this tomorrow!

**Comment by edenbrack** [comment]
i also see this not being correct for anything much smaller than 850px - it needs to flip sides much earlier on in the graph on mobile in example. mobile is going to need a media query in the css to slim up the tooltip as well which i can sort now.

**Comment by duncangeere** [comment]
Alright, so there's three components to the x-position of the tooltip in line 142 of [chart.js](https://github.com/Storythings/2017databreaches/blob/master/chart.js).

- `document.getElementById("chartgoeshere").offsetLeft` = distance from the edge of the page to the edge of the chart. I'll call this `pageOffset`.
- `x(data.records)` = distance from the edge of the chart to the centre of the point. I'll call this `chartOffset`.
- `70` = distance from the centre of the point to the left edge of the tooltip. I'll call this `pointOffset`.

The tooltip is `300px` wide right now, though we're going to adjust that with the media query, so I'll just call it `tipWidth`. I'll call the width of the whole page `pageWidth`.

So I think the code looks something like:
```
if ((pageOffset + chartOffset + pointOffset + tipWidth) > pageWidth) {
    // i.e. the right side of the tooltip goes off the edge of the page
    .style("right", (pageOffset + chartOffset - pointOffset + "px");
} else {
    // i.e. the right side of the tooltip doesn't go off the edge of the page
    .style("left", (pageOffset + chartOffset + pointOffset + "px");
}
```

Does that make sense? I don't have heaps of time to work on this today, because I've got to sort out the Reading List for ID Question, but I'm happy to answer any questions that pop up!

**Comment by duncangeere** [comment]
Fixed!
