### ISSUE TITLE
Axis tweaks

### ISSUE THREAD

**Issue by duncangeere** [Storythings/2017databreaches#16]
Y axis: Just month names, no "2017" Maybe 90 degree rotation
X axis: Moved to the top, label added so people know what the axis refers to. Maybe a bit more space above?

Anything else @edenbrack?

**Comment by edenbrack** [comment]
X-axis labels are an overlapping mess at the moment. Either try something like 10K 10M for label wording or set wrappers for each.

**Comment by duncangeere** [comment]
I think this is fixed. If you agree @edenbrack then close this issue :)
