### ISSUE TITLE
Extra page furniture

### ISSUE THREAD

**Issue by duncangeere** [Storythings/2017databreaches#18]
Darren has pasted a load of stuff into Slack that needs to go onto the page.

**Comment by duncangeere** [comment]
![image](https://user-images.githubusercontent.com/11523915/35387700-1764743a-01d1-11e8-8da5-921c8646524a.png)
Here's what we're working off for the time being.

BG colour will be `#272924`. Text colour TBC, but basically a little off-white.

**Comment by mrdarrengarrett** [comment]
Try f4eedf for white?

**Comment by duncangeere** [comment]
I merged in your pull request @edenbrack. MEGALOGOS :)

**Comment by edenbrack** [comment]
megalogos?

**Comment by duncangeere** [comment]
MEGALOGOS! 

![image](https://user-images.githubusercontent.com/11523915/35396125-6243a154-01ec-11e8-92c4-4d97c6ae2962.png)

![image](https://user-images.githubusercontent.com/11523915/35396151-6e459ce6-01ec-11e8-8351-883cfedcad26.png)

**Comment by edenbrack** [comment]
just pull requested the js to change the graph color but otherwise i think you'll need to clear your cache because i don't have megalegos on my live or local versions.

**Comment by duncangeere** [comment]
I’ll check it when I get to the hotel this evening :)

**Comment by edenbrack** [comment]
- Right-aligned ID QUESTION
- White background to tooltips
- Black/grey text on tooltips
- Dates to tooltips
- Rid of auto margins
- White axes and labels and title
- Chart title - 20px
- Social media colour matching palette
- Text matches width of picture of series intro
- Optimize images

**Comment by mrdarrengarrett** [comment]
@edenbrack Yep. I'll get you a static logo image for this page.

**Comment by duncangeere** [comment]
White axes and labels are done. Dates to Tooltips done. Tooltip logic back done.

**Comment by edenbrack** [comment]
- Hyperlink THE ID QUESTION & series logo - needs live link when available
- Hyperlink Facebook & Twitter to share article on respective platforms
- Newsletter sign up email input and button using MailChimp
- Replace text content when available

**Comment by duncangeere** [comment]
- [x] Hyperlink THE ID QUESTION & series logo - needs live link when available
- [x] Hyperlink Facebook & Twitter to share article on respective platforms
- [ ] Newsletter sign up email input and button using MailChimp
- [ ] Replace text content when available - I'm working on this!

**Comment by duncangeere** [comment]
OK, I think our list here is now complete, so I'm closing this. Good work everyone!
