### ISSUE TITLE
Static version for Medium

### ISSUE THREAD

**Issue by duncangeere** [Storythings/2017databreaches#19]
Something else to think about - we’ll need to generate a static version of this to sit on the Medium page and be clickable. What should that depict?

**Comment by mrdarrengarrett** [comment]
So maybe a zoomed in screenshot of one circle maybe? Something along those lines - def not showing a preview of the whole thing.

**Comment by mrdarrengarrett** [comment]
Yep. Definitely want it to be a compelling must click tease.

**Comment by duncangeere** [comment]
Something like this? 
![image](https://user-images.githubusercontent.com/11523915/35516308-b9885c12-050b-11e8-9af2-113ae4329f57.png)

**Comment by edenbrack** [comment]
i think so - it may work better w/out the axis in view and tooltip revealed

**Comment by duncangeere** [comment]
More like this?
![image](https://user-images.githubusercontent.com/11523915/35516503-43f87378-050c-11e8-9987-586265298bb6.png)

**Comment by duncangeere** [comment]
I believe this is the final version, so I'm closing this.
![biggestbreaches-graphic-3](https://user-images.githubusercontent.com/11523915/35571028-39498ad2-05d1-11e8-9dbc-b6a43a61238b.jpg)
