### ISSUE TITLE
Responsiveness in page layout

### ISSUE THREAD

**Issue by duncangeere** [Storythings/2017databreaches#3]
We want the page to look good on mobile and desktop. What layout adjustments do we need to achieve that?

**Comment by duncangeere** [comment]
@edenbrack This is the one :)

**Comment by edenbrack** [comment]
Responsive page layout working - only thing left to correct here is making the x-axis labels fit/not overlap each other.

**Comment by duncangeere** [comment]
I think we're sorted here. Didn't know it'd be as simple as two lines of code!
