### ISSUE TITLE
Visual clarity

### ISSUE THREAD

**Issue by edenbrack** [Storythings/2017databreaches#8]
Needs to be increased for both desktop and mobile.

**Comment by duncangeere** [comment]
Which elements do you mean? Axis labels are probably the most important, I would say...

**Comment by duncangeere** [comment]
Additionally:
We need alternating blocks of colour in the background of the chart to differentiate the months.

Should the circles have some transparency, so it's easy to see when they overlap? Will that work with the colour transitions?

**Comment by duncangeere** [comment]
Added some transparency, it doesn't work that great with the colour transitions. This page has some more info: https://bost.ocks.org/mike/transition/

**Comment by edenbrack** [comment]
I've forked the files and pushed an updated chart.js to my branch (I believe?) in order to bump the axes up to 14px.

**Comment by edenbrack** [comment]
This looks useful for the alternating blocks of colour on the y-axes but I'm struggling to make sense of it myself. https://bl.ocks.org/mbostock/3371592

**Comment by duncangeere** [comment]
I've removed the transparency and instead added a method in #12 that brings a circle to the front when you mouseover it.

We need to make the axis font Futura to match the rest of the page.

**Comment by duncangeere** [comment]
Axis font is now Futura. Gonna work on background colour blocks next.

**Comment by duncangeere** [comment]
We now have background squares, via #14 .

**Comment by duncangeere** [comment]
Slightly darker background squares requested :)

**Comment by duncangeere** [comment]
I think all of these have been done, right? Closing, and feel free to re-open if there's something missing.
